name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
